### ISSUE TITLE
Combine with Livewire

### ISSUE THREAD

**Issue by maurocasas** [cbl/blade-script#3]
Wondering, how can we include {{ }} blade tags to render code prior to the transpilation

**Comment by cbl** [comment]
Hi maurocasas,

This is not possible inside scripts that are written inside the `x-script` tag. The scripts are transpiled and minified before the view gets rendered. This is necessary to be able to cache the compiled scripts.

I would recommend to have an extra `script` tag with variables that you want to be able to access:

```html
<script>
const state = {{ $state }};
</script>
<x-script>
// Access state here.
</x-script>
```
